// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","icon":"HomeOutlined","path":"/home","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"登陆","icon":"HomeOutlined","path":"/sign","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"3"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__home__index" */'@/pages/home/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__sign__index" */'@/pages/sign/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/lly/notes/解决方案/前端权限设计与实现/React/umi4-auth/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
